#!/bin/bash

envFile="$1"
shift

# @description echos STDIN to the log file, prefixing each line with a datestamp; used via pipe
# @noargs
function xport() {
  local line
  while IFS= read -r line; do
    if [[ "$envFile" == "/etc/environment" ]]; then
      echo "$line" >> "$envFile"
    else
      echo "export $line" >> "$envFile"
    fi
  done
}

echo "HEALTHCHECK_PATH=$HEALTHCHECK_PATH" | xport

# Add executable paths to /etc/environment for easier handling in PHP code without worrying about the PATH
for i in "$@"
do
  echo "Checking for '$i'"
  iPath=$(which "$i")
  if [ -n "$iPath" ]; then
    prefix="PATH_"
    suffix=$(echo "$i" | tr '[:lower:]' '[:upper:]')
    echo "${prefix}${suffix}=${iPath}" | xport
  fi
done

