[PHP]
memory_limit = ${PHP_MEMORY_LIMIT}
max_execution_time = ${PHP_MAX_EXECUTION_TIME}
upload_max_filesize = ${PHP_UPLOAD_MAX_FILE_SIZE}
post_max_size = ${PHP_POST_MAX_SIZE}
max_input_time = ${PHP_MAX_INPUT_TIME}
max_input_vars = ${PHP_MAX_INPUT_VARS}
display_errors = ${PHP_DISPLAY_ERRORS}
error_reporting = ${PHP_ERROR_REPORTING}
error_log = ${PHP_ERROR_LOG}
; https://symfony.com/doc/current/performance.html#configure-the-php-realpath-cache
realpath_cache_size = ${PHP_REALPATH_CACHE_SIZE}
realpath_cache_ttl = ${PHP_REALPATH_CACHE_TTL}

[Date]
date.timezone = ${PHP_DATE_TIMEZONE}

[Session]
session.gc_maxlifetime = 14400
session.cookie_secure = ${PHP_SESSION_COOKIE_SECURE}

[opcache]
opcache.enable=${PHP_OPCACHE_ENABLE}
opcache.enable_cli=${PHP_OPCACHE_ENABLE}
opcache.memory_consumption=${PHP_OPCACHE_MEMORY_CONSUMPTION}
opcache.interned_strings_buffer=${PHP_OPCACHE_INTERNED_STRINGS_BUFFER}
opcache.max_accelerated_files=${PHP_OPCACHE_MAX_ACCELERATED_FILES}
opcache.revalidate_freq=${PHP_OPCACHE_REVALIDATE_FREQ}
; https://symfony.com/doc/current/performance.html#don-t-check-php-files-timestamps
opcache.validate_timestamps=${PHP_OPCACHE_VALIDATE_TIMESTAMPS}