#!/bin/bash
echo "Fixing sources.list for Stretch..."
echo "-------------------------------------"
rm /etc/apt/sources.list
{
  echo "deb http://archive.debian.org/debian/ stretch main non-free contrib"
  echo "deb http://archive.debian.org/debian-security stretch/updates main contrib non-free"
} > /etc/apt/sources.list
apt-get update -o Acquire::AllowInsecureRepositories=true && apt-get install -y --allow-unauthenticated -o Acquire::AllowInsecureRepositories=true -o Acquire::AllowDowngradeToInsecureRepositories=true debian-archive-keyring
echo "deb http://archive.debian.org/debian stretch-backports main contrib non-free" >> /etc/apt/sources.list
echo "-------------------------------------"
echo "DONE!"