#!/bin/bash

myDir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
myVersion="1.0"

# shellcheck source=./functions/_out.sh
source "$myDir/functions/_out.sh"
# shellcheck source=./functions/_dockerhub.sh
source "$myDir/functions/_dockerhub.sh"
# shellcheck source=./functions/_hcl.sh
source "$myDir/functions/_hcl.sh"

## region ############################################## BuildX

# @description Evaluates if the buildx plugin is installed
# @noargs
# @exitcode 0 Buildx Installed
# @exitcode 1 Buildx Not Installed
function has-buildx() {
  docker info 2> /dev/null | grep -q "buildx"
}

# @description Prints the builder name currently being used by the buildx plugin.
# @noargs
# @stdout string Builder Name (or empty string)
function buildx-name() {
  docker buildx inspect 2> /dev/null | grep "Name:" | awk -F":" '{ print $2 }' | head -1 | xargs
}

function buildx-install() {
  local status
  echo "Installing Docker buildx" | notify
  cronic docker buildx build . \
    && docker buildx create --name "$dhUser" \
    && docker buildx use "$dhUser"
  status=$?
  if [[ $status -eq 0 ]]; then
    echo "SUCCESS" | success | badge
  else
    echo "ERROR" | error | badge
  fi
  return "$status"
}

## region ############################################## Fork

function fork-repo() {
  local status
  echo "Performing Git Operations" | notify
  cronic git remote rename origin upstream \
    && git remote add origin "$targetRepo" \
    && git remote set-url --push upstream DISABLE \
    && git push -u origin main \
    && git checkout -b "$branch" \
    && git push -u origin "$branch" \
    && gh repo edit --default-branch "$branch" \
    && git remote set-head origin -a
  status=$?
  if [[ $status -eq 0 ]]; then
    echo "SUCCESS" | success | badge
  else
    echo "ERROR" | error | badge
  fi
  return "$status"
}

## endregion ########################################### End Fork

## region ############################################## Upstream
function push-force-with-lease() {
  local status
  echo "Pushing " | notify
  cronic git push origin "$currentBranch" --force-with-lease
  status=$?
  if [[ $status -eq 0 ]]; then
    echo "SUCCESS" | success | badge
  fi
  return "$status"
}

function pull-upstream() {
  local status isPush

  isPush=false
  [ "$1" == "--push" ] && isPush=true

  echo "Performing Git Operations" | notify
  cronic git checkout main && \
    git pull upstream main && \
    git checkout "$currentBranch" && \
    git rebase main --autostash
  status=$?
  if [[ $status -eq 0 ]]; then
    echo DONE | success | badge
    echo ""
    echo "Successfully rebased ${currentBranch} onto changes from ${upstreamRepo}:main."
    echo "Any uncommitted changes were automatically stashed and restored."
    if $isPush || ask "Would you like to push to origin/${currentBranch} now?"; then
      echo ""
      if ! push-force-with-lease; then
        return 1
      fi
    else
      echo ""
      echo "You can push later with:${RESET} vat push origin ${currentBranch} --force-with-lease"
      echo ""
    fi
    return 0
  else
    echo "$HR"
    echo "⚠️  ${RED}REBASE PAUSED DUE TO CONFLICTS${RESET} ⚠️"
    echo "$HR"
    echo "To FIX:   1. Edit the files with conflicts."
    echo "          2. run 'vat add <file>'"
    echo "          3. run 'vat rebase --continue'"
    echo ""
    echo "To ABORT: run 'vat rebase --abort'"
    echo "          (This returns ${currentBranch} to its original state)"
    echo "$HR"
    return 1

  fi
  return "$status"
}

## endregion ########################################### End Upstream

## region ############################################## Stir


## endregion ########################################### End Stir

## region ############################################## Controller Functions

function validate_dockerhub() {
  [ -z "$dhUser" ] &&
    echo "No Docker Hub username was found." || error
    echo "Please supply this with the --user <username> flag for the first run." | error && return 1
  exit 1
}
function validate_fork() {

  [ -z "$privateRepo" ] &&
    echo "You must provide the name of the repo." | error && return 1

  [ -z "$branch" ] &&
    echo "You must provide the name of your primary branch" | error && return 1

  ! gh auth status >/dev/null 2>&1 &&
    echo "Error: Not Logged in to GitHub. Run 'vat auth login' first." | error && return 1

  return 0
}

function validate_pull() {

  ! $isGitRepo &&
    echo "You must run this command from a Git repo!" | error && return 1

  ! $isGitUpstream &&
    echo "You must initialize your repo by running the command "vat clone" first." | error && return 1

  [ -z "$primaryBranch" ] &&
    echo "Could not detect primary branch from the GitHub CLI." | error && return 1

  [ "$currentBranch" != "$primaryBranch" ] &&
    echo "You are on '$currentBranch'; Run this utility from '$primaryBranch'" | err && return 1

  return 0
}

function action_gh() {
  gh "$@"
}

function action_git() {
  git "$@"
}

function action_pull() {
  local isUpstream

  isUpstream=false
  while [ "$1" != "" ]; do
    if [ "$1" == "--upstream" ]; then
      isUpstream=true
    fi
  done

  if $isUpstream; then
    validate_pull || return $?
    pull-upstream "$@"
  else
    action_git pull "$@"
  fi
}

function action_fork() {
  while [ "$1" != "" ]; do
    case "$1" in
      --branch )
          branch="$2"
          shift
          ;;
      --* )
          usage && return 1
          ;;
      * )
          [ -n "$targetRepo" ] && usage && return 1
          targetRepo="$1"
          ;;
    esac
    shift
  done

  if [ -z "$privateRepo" ]; then
    privateRepo=$(ask-text "What is the name of your private container repo?")
  fi

  if [ -z "$branch" ]; then
    echo "${BLUE}To avoid upstream conflicts, you cannot use 'main' as the primary branch of your repo.${RESET}"
    echo "${BLUE}This branch will be automatically created and marked as primary branch.${RESET}"
    echo ""
    branch=$(ask-text "What should the name of your primary branch be?")
  fi

  validate_fork || return $?
  fork-repo
}

## endregion ########################################### End Controller Functions

## region ############################################## Routing

isGitRepo=false
isGitUpstream=false

if git rev-parse --is-inside-work-tree > /dev/null 2>&1; then
  isGitRepo=true
  if git remote | grep -q "upstream"; then
    isGitUpstream=true
    primaryBranch=$(gh repo view --json defaultBranchRef --jq '.defaultBranchRef.name')
    currentBranch=$(git branch --show-current)
    upstreamUrl=$(git remote get-url upstream)
    # shellcheck disable=SC2001
    upstreamRepo=$(echo "$upstreamUrl" | sed 's#https://github.com/##')
  fi
fi

ghCore=$(gh help | awk '/CORE COMMANDS/{flag=1;next}/GITHUB ACTIONS COMMANDS/{flag=0}flag' | awk -F':' '{ print $1 }' | xargs | sed 's/ /|/g')
isStir=false
while [ "$1" != "" ]; do
  # Check flags
  # shellcheck disable=SC2254
  case "$1" in
    $ghCore)           action_gh "$@" ;;
    build|bake|stir )  shift; isStir=true ;;
    pull )             shift; action_pull "$@" ;;
    fork|clone )       shift; action_fork "$@" ;;
    --version )        shift; action_version "$@"; exit ;;
    --help )           shift; action_usage "$@"; exit ;;
  esac
done

if ! $isStir; then
  git "$@"
  exit $?
fi

## endregion ########################################### End Routing

## region ###################################### Argument Handling

isNoCache=false
isPush=false
PLATFORMS=""
BUILD_ARG_STRING=""
BUILD_ARGS=()
while [ "$1" != "" ]; do
  # Check flags
  case "$1" in
  --no-cache )                BUILD_ARGS+=("--no-cache"); ;;
  --push )                    BUILD_ARGS+=("--push");        ;;
  --user )                    dhUser="$2"; shift; ;;
  --arm64 )                   PLATFORMS="$PLATFORMS,linux/arm64" ;;
  --amd64 )                   PLATFORMS="$PLATFORMS,linux/amd64" ;;
  --platforms )               PLATFORMS="$2"; shift; ;;
  --tag )                     BUILD_ARGS+=("--var" "TAG=$2"); shift ;;
  --var )                     BUILD_ARGS+=("--var" "$2"); shift ;;
  * )                         bakePath="$1" ;;
  esac
  shift # move to next kv pair
done

if [ -n "$PLATFORMS" ]; then
  PLATFORMS=$(echo "$PLATFORMS" | sed 's/^,//') # Remove leading comma if exists
fi

cachedDhUser=$(dockerhub::username::cached)
# If not set, Docker Hub username From environment
[ -z "$dhUser" ] && [ -n "$COMPOSE_USER" ] && dhUser="$COMPOSE_USER"
# If not set, Docker Hub username from Docker cached credentials
[ -z "$dhUser" ] && dhUser="$cachedDhUser"
# If not set, Docker Hub username from the machine hostname
[ -z "$dhUser" ] && dhUser="$(dockerhub::username::domain)"

## endregion ################################### End Argument Handling

## endregion ################################### End Functions

projPath=$(pwd)
imageDir=$(dirname "$projPath")
projName=$(basename "$projPath")
imageName="$projName"
dockerfile="$projPath/Dockerfile"

#
# Docker Login
#

if [ -z "$dhUser" ]; then
  # We have to have a username to start off
  echo "${RED}No Docker Hub username was found. Please supply this with the --user <username> flag for the first run.${RESET}"
  exit 1
elif [[ "$dhUser" != "$cachedDhUser" ]]; then
  # If the username differs, then we need to log out & log in
  echo "$HR"
  ! docker logout && echo "$HR" && exit 1
  ! docker login --username "$dhUser" && echo "$HR" && exit 1
  echo "$HR"
elif [ -z "$cachedDhUser" ]; then
  # If we have a username, but no cached credentials, then we need to log in
  ! docker login --username "$dhUser" && echo "$HR" && exit 1
  echo "$HR"
fi

#
# Docker BuildX Plugin
#
if ! has-buildx; then
  ask "Docker buildx plugin not found. Install?" || exit 1

else
  # Just check if we have a builder, and are using it
  buildxName=$(buildx-name)
  if [ -z "$buildxName" ]; then
    echo "$HR"
    # Determine if our builder name is already in the list
    if ! docker buildx ls 2> /dev/null | grep -v "error" | grep -q "$dhUser"; then
      ! docker buildx create --name "$dhUser" && echo "$HR" && exit 1
    fi
    # Use the builder
    ! docker buildx use "$dhUser" && echo "$HR" && exit 1
    echo "$HR"
  fi
fi

# Build the Question
if [ -n "$dhUser" ]; then
  imageTarget="$dhUser/${imageName}:latest"
else
  imageTarget="${imageName}:latest"
fi

if [ -n "$PLATFORMS" ]; then
  platformsTxt="$PLATFORMS"
else
  platformsTxt=$(hcl-get-platforms "$projPath/docker-bake.hcl" | jq -r 'join(",")')
fi

if [ -n "${BUILD_ARGS[*]}" ]; then
  ASKING="Proceed with building ${imageTarget/#\//} for $platformsTxt with ${BUILD_ARGS[*]}?"
else
  ASKING="Proceed with building ${imageTarget/#\//} for $platformsTxt?"
fi

if ! ask "$ASKING"; then
  echo "Aborting build..."
  exit 0
fi

#
# Determine the includes needed
#

bakeJson=$(hcl2json < "$projPath/docker-bake.hcl")
bakeTarget=$(jq --arg target "${projName/./}" '.target[$target][]//empty' <<< "$bakeJson")
if [ -n "$bakeTarget" ]; then
  bakePhp=$(jq -r '.variable.PHP_VERSION[].default//empty' <<< "$bakeJson")
  bakeContext=$(jq '.contexts' <<< "$bakeTarget")
  while IFS="|" read -r key value; do
    if echo "$value" | grep -q "target:"; then
      target=$(echo "$value" | sed 's/^target://' | sed "s/\${PHP_VERSION}/$bakePhp/")
      same=$(jq --arg target "$target" '.target[$target][0]//empty' <<< "$bakeJson")
      if [ -z "$same" ]; then
        file=$(hcl-find-target "$projPath" "$target")
        if [ -n "$file" ]; then
          BUILD_ARGS+=("-f" "$file")
        else
          echo "Missing $target! Exiting..."
          exit 1
        fi
      fi
    fi
  done < <(jq -r 'to_entries[] | "\(.key)|\(.value)"' <<< "$bakeContext")
fi
BUILD_ARGS+=("-f" "$projPath/docker-bake.hcl")

if [ -n "$PLATFORMS" ]; then
  BUILD_ARGS+=("--var" "PLATFORMS=$PLATFORMS")
fi

if [ -n "$dhUser" ]; then
  BUILD_ARGS+=("--var" "DOCKERHUB_USER=$dhUser")
fi

echo "$HR"
if docker buildx bake "${BUILD_ARGS[@]}" "${projName/./}"; then
  echo "$HR"
  exit 0
else
  echo "$HR"
  echo "${RED}Build Process failed. Scroll up in the logs to find the error, then correct the issue.${RESET}"
  echo ""
fi
exit









