;
; Global Settings
; (See /usr/local/etc/php-fpm.conf for available settings.)
;
; 💪 Pool Settings
; (See /usr/local/etc/php-fpm.d/www.conf.default for available settings.)
;
[www]
; Process Management Settings
pm = ${PHP_FPM_PM_CONTROL}
pm.max_children = ${PHP_FPM_PM_MAX_CHILDREN}
pm.start_servers = ${PHP_FPM_PM_START_SERVERS}
pm.min_spare_servers = ${PHP_FPM_PM_MIN_SPARE_SERVERS}
pm.max_spare_servers = ${PHP_FPM_PM_MAX_SPARE_SERVERS}

; Healthcheck settings
pm.status_path = /status
ping.path = /healthcheck
ping.response = OK
security.limit_extensions = .php .healthcheck /healthcheck

; Environment Settings
clear_env = no