# Allow the Authorization header to pass through to PHP-FPM natively
# With fallback for mechanism specifically for Jessie-era Apache
<Directory "/">
    <IfModule mod_version.c>
        <IfVersion >= 2.4.13>
            CGIPassAuth On
        </IfVersion>
        <IfVersion < 2.4.13>
            <IfModule mod_rewrite.c>
                RewriteEngine On
                RewriteCond %{HTTP:Authorization} .
                RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
            </IfModule>
        </IfVersion>
    </IfModule>
</Directory>

# PHP-FPM
<FilesMatch \.php$>
    SetHandler "proxy:fcgi://127.0.0.1:9000"
</FilesMatch>

# Basic Configuration
DirectoryIndex disabled
DirectoryIndex index.php index.html
<Directory /var/www/>
    Options -Indexes
    AllowOverride All
</Directory>

# Healthchecks: Set /healthcheck to be the healthcheck URL
ProxyPass "/healthcheck" "fcgi://localhost:9000/healthcheck"
ProxyPassReverse "/healthcheck" "fcgi://localhost:9000"

# Set the Proxy Timeout to be 30 minutes
ProxyTimeout 1800

# Set environment variable for healthcheck requests
SetEnvIf Request_URI "^/healthcheck$" dontlog

# CustomLog directive to conditionally log requests (combined log, sent to stdout for Docker)
LogFormat "%l %u %t %v %a \"%r\" %>s %b" commonvhost
CustomLog ${APACHE_LOG_DIR}/access.log commonvhost env=!dontlog
CustomLog /proc/self/fd/1 commonvhost env=!dontlog
ErrorLog ${APACHE_LOG_DIR}/error.log
ErrorLog /proc/self/fd/2

# Configure Log Level
LogLevel ${LOG_LEVEL}

# Disable Server Signature for increased security
ServerSignature Off